src/main.rs

Rusqlite's transaction w/ the borrow checker is a real PITA. This is a bandaid (or maybe long term approach) to prevent db corruption for killed processes.

Add in simple transactions

---

migrations/01-initial/up.sql
src/main.rs
src/models/block_group.rs
src/models/edge.rs
src/models/path.rs
src/models/sequence.rs

Support storing sequences on disk instead of in db.
The builder pattern is used here, as it allows other defaults to be set automatically which was not possible in the default pattern.
Given that the sequence itself needs some inference to know how to fetch it, sequence was made private as well.

Support sequences stored on disk

---

src/main.rs
src/models.rs
src/models/block_group.rs
src/models/edge.rs

Previous clone update omitted non-path edge ids.

Clone edge ids with block group clone

---

docs/commands.md
fixtures/simple2.vcf
migrations/operations/01-initial/up.sql
src/main.rs
src/models/operations.rs
src/operation_management.rs

Adds in support for branches and moving between branches. Not in yet is applying changes between branches.

Operation branch support

---

docs/commands.md
migrations/operations/01-initial/up.sql
src/imports/fasta.rs
src/main.rs
src/models/file_types.rs
src/models/operations.rs
src/operation_management.rs
src/updates/vcf.rs

Setup for applying a changeset to a given branch.

Apply command

---

Cargo.lock
Cargo.toml
src/imports/fasta.rs
src/lib.rs
src/models/block_group.rs
src/models/block_group_edge.rs
src/models/edge.rs
src/models/operations.rs
src/models/path.rs
src/models/sequence.rs
src/models/strand.rs
src/operation_management.rs
src/test_helpers.rs
src/updates/vcf.rs

This is an extension to the changeset management to identify dependencies of a changeset and write those out. On imports, we ensure that the ids of dependent entities are created or retrieved from the current checked out database.
The workflow this handles is suppose we have branch A with operations 1->2->3, and branch B with operations 1->4->5. If we apply operation 3, things required from operation 2 may not be present. This ensures they will be. For the reversion, we create a new commit with the updates from this application (similar to a new commit id resulting from a cherry-pick).

Custom changeset management

---

src/models/operations.rs

Prevents users adding operations in the middle of a branch.

Branch bifurcation protection

---

docs/commands.md
migrations/operations/01-initial/up.sql
src/imports/fasta.rs
src/main.rs
src/models/block_group.rs
src/models/collection.rs
src/models/operations.rs
src/models/sequence.rs
src/operation_management.rs

This allows users to reset their branch to a previous state, detaching the commits from the head of the branch. I used a mask approach where the commits are hidden and not deleted. It could make it simpler to restore this way.

Reset command

---

Cargo.lock
Cargo.toml
src/imports/fasta.rs
src/main.rs
src/models/edge.rs
src/models/node.rs
src/models/sequence.rs
src/updates/vcf.rs

Caches the index file so it doesn't need to be read everytime for external sequence lookup.

Cache fasta index for external sequence lookup

---

src/models/operations.rs

If we were working off a second db, operation id 1 would always show up even if it was not part of that db.

Handle cases where branch on secondary db showed commit 1

---

Cargo.lock
Cargo.toml
src/exports/gfa.rs
src/gfa_reader.rs
src/imports/gfa.rs
src/lib.rs
src/main.rs

There's about 4 things happening here:
1. Changing segment ID to be <node ID>.<sequence start coordinate>
2. Copy/pasting in the GFA reader code from the third party crate (MIT license) so I can fix a bug with parsing a string segment ID
3. Adding a --sample flag to GFA export to limit to just one sample
4. Replacing some manual code for filtering out start/end nodes with a dedicated method

GFA export improvements

---

migrations/operations/01-initial/up.sql
src/imports/fasta.rs
src/main.rs
src/models/operations.rs
src/operation_management.rs
src/updates/fasta.rs
src/updates/gaf.rs
src/updates/library.rs
src/updates/vcf.rs

Adds hashes to make operations unique and usable across databases.
Notable stuff:
* We make operations after a changeset has been made, as I don't want to support operations with null hashes. This requires some fiddling with the start/end operation code but it ended up a bit lighter in the end.
* Sometimes we need to force the hash for easier testing, so that is why you see that.
* Operation is a Result field so we can handle errors on duplicate operations now (not done here though, but is now possible).
Lot of other stuff is just getting old methods changed to work with hashes.

Operation hashes

---

src/models/path.rs
src/operation_management.rs

The rules are:
1. No duplicate edges
2. All edges for a path must be in the path's block group
3. The target of one edge and the source of the next one must be the same node
4. The target coordinate of one edge must be before the source coordinate of the next one
5. An edge can't have the same node + coordinate as both its source and target

Add validations on edges when creating a path

---

Cargo.lock
Cargo.toml
src/imports/fasta.rs
src/imports/genbank.rs
src/main.rs
src/models/file_types.rs
src/models/operations.rs
src/operation_management.rs
src/patch.rs
src/test_helpers.rs
src/updates/fasta.rs
src/updates/gaf.rs
src/updates/library.rs
src/updates/vcf.rs

This is why I wanted a separate PR. The signature for import_genbank is a reader -- not a file path so operations couldn't be made. So I added a method to add operation info if it should be tracked. The reason for this is I felt like our import operations are a bit too constrained to create apis around. Accepting a stream of input makes it easier for supporting pipes/etc. and other non-file based inputs. Having the caller responsible for telling the function the file name instead of coupling that to the reader method (being a file-like object) gives a bit more flexibility.
I also wanted better errors here, but it required refactoring a bunch of other error calls.

Add operation for genbank

---

src/annotations/gff.rs
src/exports/fasta.rs
src/exports/genbank.rs
src/imports/fasta.rs
src/imports/genbank.rs
src/imports/gfa.rs
src/main.rs
src/models/sample.rs
src/operation_management.rs
src/patch.rs
src/updates/fasta.rs
src/updates/genbank.rs
src/updates/library.rs
src/updates/vcf.rs

So sample names can be declared at import time instead of always having to be null

Add sample creation to import

---

src/imports/fasta.rs
src/imports/genbank.rs
src/imports/gfa.rs
src/progress_bar.rs
src/updates/vcf.rs

progress bars are spamming tests.

Compile out progress bar for tests

---

Cargo.lock
Cargo.toml
src/config.rs
src/graph.rs
src/lib.rs
src/main.rs
src/models/node.rs
src/operation_management.rs
src/patch.rs
src/views.rs
src/views/patch.rs

This will generate a .dot file from a patch. It's some of the starting work to explore how we can show changes to users in reviews, etc

View patches

---

src/main.rs
src/views/patch.rs

3 minor fixes:
- Documentation updates per chat.
- I also saw segment_id being used in your dot generator, I think that was a leftover from the Python prototype. I had used a segment from the GFA vocab, but it's really a block, hence the edit.
- Deletions were drawn as dashed lines that indicate boundary edges, now they're drawn properly. It's still not complete though, because for heterozygous genomes you want to show the boundary edge as being "real" still.

Minor fixes to docs + drawing logic

---

src/operation_management.rs
src/views/patch.rs

Operation hashes don't use the db_uuid so conflicts can arise between databases. This makes sure the hash starts with the db_uuid. I did not use this in the force_hash part...yet. May in the future.

Add db_uuid to operation hash

---

src/diffs/gfa.rs
src/exports/gfa.rs
src/gfa.rs
src/models/operations.rs
src/operation_management.rs
src/patch.rs

Fixes 2 problems w/ GFA export I hit:
* not all path links were exported
* the segment line id had a * at the end that was not in spec
The stuff in operations is just warning cleanup.

GFA Export fixes

---

fixtures/vcfs/out_of_bounds.vcf
src/exports/gfa.rs
src/imports/genbank.rs
src/models/block_group.rs
src/models/edge.rs
src/models/path.rs
src/updates/fasta.rs
src/updates/genbank.rs
src/updates/vcf.rs

Found this problem when i applied a vcf to the wrong fasta. This ensures we aren't making changes outside the scope of the interval tree. I put it in setup_up_new_edges as a general catch area, but also in the vcf update code where i initially found the bug so it can bail early before parsing a few gigs of vcf.

Check if position is beyond path length

---

src/graph_operators.rs
src/main.rs
src/models/block_group.rs

Example usage:
```
cargo run -- init
cargo run -- import --fasta fixtures/simple.fa
cargo run -- update --fasta fixtures/aa.fa --start 3 --end 5 --region-name m123 --new-sample test1
cargo run -- update --fasta fixtures/aa.fa --start 15 --end 20 --region-name m123 --sample test1 --new-sample test2
cargo run -- derive-chunks --new-sample splits --region m123 --breakpoints 1,8,25 --sample test2
cargo run -- view -s splits m123.2
```

Add operation to derive chunks

---

src/main.rs
src/views/block_group.rs

In the final commit to my previous PR I had added a connection refreshing routine that opened and closed the db connection. That was overkill and by using Connection::open instead of get_connection it introduced a new bug (Connection::open does not load he extensions that other methods rely on). Now we're not changing the conn at all.

Viewer - handle synchronization to external changes

---

src/graph_operators.rs
src/main.rs
src/models/block_group.rs
src/models/block_group_edge.rs
src/models/edge.rs
src/test_helpers.rs

Add "make stitch" operation.
```
cargo run -- init
cargo run -- import --fasta fixtures/simple.fa
cargo run -- update --fasta fixtures/aa.fa --start 3 --end 5 --region-name m123 --new-sample test1
cargo run -- update --fasta fixtures/aa.fa --start 15 --end 20 --region-name m123 --sample test1 --new-sample test2
cargo run -- derive-chunks --new-sample splits --region m123 --breakpoints 1,8,25 --sample test2
cargo run -- view -s splits m123.2
cargo run -- make-stitch --sample splits --new-sample stitched --regions m123.2,m123.3 --new-region m123.2-3
```

Add make stitch operation
